
# The transformations process in the order listed here.
from openldap_opencensus_stats.config_transformers.base import ConfigurationTransformationChainSingleton
from openldap_opencensus_stats.config_transformers.snake_case import SnakeCaseConfigurationTransformer
from openldap_opencensus_stats.config_transformers.metric_dn import MetricDnConfigurationTransformer
from openldap_opencensus_stats.config_transformers.copy_for_each_database import CopyForEachDatabaseConfigurationTransformer
from openldap_opencensus_stats.config_transformers.child_object import ChildObjectConfigurationTransformer
from openldap_opencensus_stats.config_transformers.metric_name_interpolation import MetricNameInterpolationConfigurationTransformer
from openldap_opencensus_stats.config_transformers.metric_name import MetricNameConfigurationTransformer
from openldap_opencensus_stats.config_transformers.metric_query_dn import MetricQueryDnConfigurationTransformer
ConfigurationTransformationChainSingleton().register(MetricDnConfigurationTransformer)