
# The transformations process in the order listed here.
from ldapstats.config_transformers.base import ConfigurationTransformationChainSingleton
from ldapstats.config_transformers.snake_case import SnakeCaseConfigurationTransformer
from ldapstats.config_transformers.metric_dn import MetricDnConfigurationTransformer
from ldapstats.config_transformers.copy_for_each_database import CopyForEachDatabaseConfigurationTransformer
from ldapstats.config_transformers.child_object import ChildObjectConfigurationTransformer
from ldapstats.config_transformers.metric_name_interpolation import MetricNameInterpolationConfigurationTransformer
from ldapstats.config_transformers.metric_name import MetricNameConfigurationTransformer
from ldapstats.config_transformers.metric_query_dn import MetricQueryDnConfigurationTransformer
ConfigurationTransformationChainSingleton().register(MetricDnConfigurationTransformer)